# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sledge-Plugin-DI
version:      v0.0.1
version_from: lib/Sledge/Plugin/DI.pm
installdirs:  site
requires:
    Test::Base:                    0
    Test::More:                    0
    UNIVERSAL::require:            0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
